/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.Random;


class MainTest {
    @Test
    public void testQuotes() {
        Gson gson = new Gson();
        String path = "../app/src/test/resources/recentquotes.json";
        try (Reader reader = new FileReader(path)) {
            RecentQuotes[] recentQuotes = gson.fromJson(reader, RecentQuotes[].class);
            Random r= new Random();
            int index = r.nextInt(recentQuotes.length);
            String expected =
                    "RecentQuotes{" +
                            "author='" + "Marilyn Monroe" + '\'' +
                            ", text='" + " “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” "+ '\'' +
                            '}';
            String output = recentQuotes[0].toString();
            Assertions.assertEquals(expected,output);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            Assertions.assertTrue(false);
        }
    }

}
