
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Path;
import java.util.Random;

public class Main {
    public static void main(String[] args) throws IOException {
        Gson gson = new Gson();
        String path = "app/src/main/resources/recentquotes.json";
        try (Reader reader = new FileReader(path)) {
            RecentQuotes[] recentQuotes = gson.fromJson(reader, RecentQuotes[].class);
            Random r= new Random();
            int index = r.nextInt(recentQuotes.length);
            System.out.println(recentQuotes[0]);
        }catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }
}